title: <p align="center"> Vishwanath Patil </p>
logo: /assets/img/vishwanath_g_patil_50.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/vishwanath-patil-4a22132b/">LinkedIn</a> |
  <a href="https://github.com/vishwaszon">GitHub</a>
  
  <br>   
  I have around 7 years of experience in Automotive domain.Currently working in L&T Technology services.
  My work currently is on CAE analysis.
  I am also pursuing Executive program in Machine learning and Artificial inteligence in Updrad.
  I aim to work in ML/AI domain.
  <br>
  </p>


theme: jekyll-theme-minimal
